# Generated by Django 4.2.2 on 2023-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
    ]
