# Generated by Django 4.2.2 on 2023-06-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdata_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='follow',
            field=models.ManyToManyField(blank=True, to='api.userdata'),
        ),
    ]
